-- Make stored-procedure prototype category mapping priorities explicit:
-- Gamma tags first, native Gamma category/sport fields second, keyword fallback last.

insert into gamma_tag_category_map (match_type, match_value, category_slug, priority, notes)
select match_type, match_value, category_slug, priority, 'Priority seed for stored-procedure category parity.'
from (
  values
    ('tag_slug', 'sports', 'sports', 3),
    ('tag_slug', 'geopolitics', 'geopolitics', 3),
    ('tag_slug', 'politics', 'politics', 3),
    ('tag_slug', 'crypto', 'crypto', 3),
    ('tag_slug', 'crypto-prices', 'crypto', 3),
    ('tag_slug', 'macro', 'macro', 3),
    ('tag_slug', 'economy', 'macro', 3),
    ('tag_slug', 'technology', 'technology', 3),
    ('tag_slug', 'tech', 'technology', 3),
    ('tag_slug', 'weather', 'weather', 3),
    ('tag_slug', 'culture', 'culture', 3),
    ('tag_slug', 'science', 'science', 3),
    ('tag_label', 'sports', 'sports', 3),
    ('tag_label', 'geopolitics', 'geopolitics', 3),
    ('tag_label', 'politics', 'politics', 3),
    ('tag_label', 'crypto', 'crypto', 3),
    ('tag_label', 'macro', 'macro', 3),
    ('tag_label', 'technology', 'technology', 3),
    ('tag_label', 'weather', 'weather', 3),
    ('tag_label', 'culture', 'culture', 3),
    ('tag_label', 'science', 'science', 3),
    ('category_slug', 'sports', 'sports', 5),
    ('category_slug', 'geopolitics', 'geopolitics', 5),
    ('category_slug', 'politics', 'politics', 5),
    ('category_slug', 'crypto', 'crypto', 5),
    ('category_slug', 'crypto-prices', 'crypto', 5),
    ('category_slug', 'macro', 'macro', 5),
    ('category_slug', 'economy', 'macro', 5),
    ('category_slug', 'technology', 'technology', 5),
    ('category_slug', 'tech', 'technology', 5),
    ('category_slug', 'weather', 'weather', 5),
    ('category_slug', 'culture', 'culture', 5),
    ('category_slug', 'science', 'science', 5),
    ('category_label', 'sports', 'sports', 5),
    ('category_label', 'geopolitics', 'geopolitics', 5),
    ('category_label', 'politics', 'politics', 5),
    ('category_label', 'crypto', 'crypto', 5),
    ('category_label', 'macro', 'macro', 5),
    ('category_label', 'technology', 'technology', 5),
    ('category_label', 'weather', 'weather', 5),
    ('category_label', 'culture', 'culture', 5),
    ('category_label', 'science', 'science', 5),
    ('sport', 'esports', 'sports', 6),
    ('sport', 'sports', 'sports', 6),
    ('sport', 'basketball', 'sports', 6),
    ('sport', 'baseball', 'sports', 6),
    ('sport', 'football', 'sports', 6),
    ('sport', 'soccer', 'sports', 6),
    ('sport', 'tennis', 'sports', 6),
    ('sport', 'hockey', 'sports', 6),
    ('sport', 'golf', 'sports', 6),
    ('sport', 'cricket', 'sports', 6),
    ('sport', 'mma', 'sports', 6),
    ('sport', 'boxing', 'sports', 6),
    ('sport', 'formula-1', 'sports', 6),
    ('sport', 'f1', 'sports', 6)
) as seeded(match_type, match_value, category_slug, priority)
on conflict (source, match_type, lower(match_value)) do update set
  category_slug = excluded.category_slug,
  priority = excluded.priority,
  is_active = true,
  notes = excluded.notes,
  updated_at = now();
