export type PolymarketMarket = {
  id?: string;
  conditionId?: string;
  slug?: string;
  question?: string;
  title?: string;
  description?: string;
  category?: string;
  active?: boolean;
  closed?: boolean;
  resolved?: boolean;
  archived?: boolean;
  endDate?: string;
  endDateIso?: string;
  resolutionDate?: string;
  closeTime?: string;
  closedTime?: string;
  updatedAt?: string;
  liquidity?: string | number;
  liquidityClob?: string | number;
  liquidityNum?: string | number;
  volume24h?: string | number;
  volume24H?: string | number;
  volume24hr?: string | number;
  volume24hrClob?: string | number;
  volume?: string | number;
  volumeNum?: string | number;
  lastTradePrice?: string | number;
  bestAsk?: string | number;
  bestBid?: string | number;
  outcomePrices?: string | string[] | number[];
  outcomes?: string | string[];
  clobTokenIds?: string | string[];
  tokens?: Array<{
    token_id?: string;
    tokenId?: string;
    outcome?: string;
    name?: string;
    label?: string;
    price?: string | number;
  }>;
  tags?: Array<{ label?: string; name?: string; slug?: string } | string>;
};

export type PolymarketTrade = {
  id?: string;
  conditionId?: string;
  condition_id?: string;
  market?: string;
  marketId?: string;
  market_id?: string;
  asset?: string;
  assetId?: string;
  tokenId?: string;
  token_id?: string;
  outcome?: string;
  makerAddress?: string;
  maker?: string;
  takerAddress?: string;
  taker?: string;
  proxyWallet?: string;
  proxy_wallet?: string;
  trader?: string;
  walletAddress?: string;
  wallet?: string;
  side?: string;
  price?: string | number;
  size?: string | number;
  amount?: string | number;
  shares?: string | number;
  usdcSize?: string | number;
  usdc_size?: string | number;
  notional?: string | number;
  transactionHash?: string;
  transaction_hash?: string;
  txHash?: string;
  tradeId?: string;
  trade_id?: string;
  orderHash?: string;
  timestamp?: string | number;
};
